# Generated by Django 4.2.19 on 2025-02-28 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=40)),
                ('numer_domu', models.CharField(max_length=5)),
                ('numer_mieszkania', models.CharField(blank=True, max_length=5, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('miasto', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
