# Generated by Django 5.1.6 on 2025-02-11 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie_text', models.CharField(max_length=200)),
                ('data_pub', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
        migrations.CreateModel(
            name='Wybor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wybor_text', models.CharField(max_length=200)),
                ('glosy', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apka.pytanie')),
            ],
        ),
    ]
